version: '3'

services:
  fogbus2-fogverse-user:
    image: ariqbasyar/fogbus2-fogverse:user
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./videos:/workplace/fogbus2-app/videos
      - ./results:/workplace/fogbus2-app/results
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workplace/fogbus2-app
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Jakarta
    privileged: true
    network_mode:
      host
    restart: unless-stopped
