version: '3'

services:
  fogbus2-fogverse-user:
    image: ariqbasyar/fogbus2-fogverse:user
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./video:/workplace/fogbus2-app/video
      - ./images:/workplace/fogbus2-app/images
      - ./result:/workplace/fogbus2-app/result
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workplace/fogbus2-app
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Jakarta
    privileged: true
    network_mode:
      host
    restart: unless-stopped
