version: '3'

services:

  fogbus2-fogverse-master:
    image: ariqbasyar/fogbus2-fogverse:master
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sources/:/workplace/
      - ./sources/.mysql.env:/workplace/.mysql.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
      PYTHONUNBUFFERED: 0
    network_mode:
      host
    restart: unless-stopped
