version: '3'

services:

  fogbus2-fogverse-remote_logger:
    image: ariqbasyar/fogbus2-fogverse:remote-logger
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sources/.mysql.env:/workplace/.mysql.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Jakarta
    network_mode:
      host
    restart: unless-stopped
