version: '3'

services:

  fogbus2-fogverse-actor:
    image: ariqbasyar/fogbus2-fogverse:actor
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Asia/Jakarta
      PYTHONUNBUFFERED: 0
    network_mode:
      host
    restart: unless-stopped